### ISSUE TITLE
Does this work in 4.0rc6?

### ISSUE THREAD

**Issue by L-B-X** [blessedcoolant/invoke_bria_rmbg#2]
Hi, First time trying a node in Invoke AI.  I may be doing something wrong but don't know where to go from here:

Using 4.0rc6 (ignore in image it says _rc5 folder - I updated it to rc6)

Cloned into <Invoke>/nodes/

Manually download model file and put into <Invoke>/models/any/bria_rmbg/

Built workflow similar to what's shown in github.  rmbg node shows up fine.  

Loaded an image into the node.  When I click the green Invoke button I get this in the console:
![Bria_rmbg_error](https://github.com/blessedcoolant/invoke_bria_rmbg/assets/22203701/b5480714-72e5-4deb-95ed-70ae1c99baee)

Any ideas?  Thank you.

**Comment by blessedcoolant** [comment]
I'll take a look. I think something got changed in the RC.

**Comment by blessedcoolant** [comment]
Just tested. Seems to be working fine. Can you share the image that is breaking it?

**Comment by L-B-X** [comment]
Actually - I just restarted the server and it seems to be working now.

I had just tried installing the other remove background node from the community nodes page - did the pip install rembg, then installed the node.  Restarted the server to see if I could get that one working - but it gave errors and went into an eternal start up loop in the cmd console.

So removed the remove background node.  Restarted - it loaded to the workflow I created for your node.

For fun - clicked the Invoke button - and it worked!!

Not sure what happened there - as I had restarted everything after installing your node first time (ahh - everything except refreshing the browser which I'd had open from earlier today).  Mind you - still don't remember refreshing it at all.

Anyway - I'm rambling - thought I'd better give you the low down on what I'd done between it giving me the error, and now - where it seems to be working.

Sorry to have disturbed you - and thanks for the amazingly quick support.

**Comment by blessedcoolant** [comment]
I think I figured out what the issue is. Something broke the variable that was holding the model in memory. I'm pushing a fix to check that and load the model if need be. So it doesn't break during the inference process no matter the state.

Thanks for catching it. Glad to hear its working on your end.

**Comment by L-B-X** [comment]
Is working great!  Thank you.

**Comment by blessedcoolant** [comment]
Pushed a change that will check for the network model each time to ensure it doesnt break for whatever reason.
