### ISSUE TITLE
Request for Video Instruction or Additional Installation Instructions

### ISSUE THREAD

**Issue by Kondzolko** [blessedcoolant/invoke_bria_rmbg#3]
Hello,

I've been learning to use AI tools, and I've been trying for a few days to install [[BRIA RMBG v1.4](https://huggingface.co/briaai/RMBG-1.4)] on my **InvokeAI v4.2.3** setup without success.

Today, I discovered your project on GitHub and followed both the manual and automatic installation instructions. However, I am unable to locate the RMBG model in the web interface.

I believe I might be missing some crucial steps or lack the necessary knowledge to properly install or locate the model within InvokeAI.

Could you please help me identify what might be going wrong? Here are the steps I followed:

I cloned the repository with:
`git clone https://github.com/blessedcoolant/invoke_bria_rmbg.git`

After cloning, I am unsure what to do next to make the model appear in the user interface.
I would greatly appreciate it if you could provide more detailed instructions or a video tutorial on how to install and use your model within InvokeAI.
![Screenshot 2024-06-02 at 10 29 03 PM](https://github.com/blessedcoolant/invoke_bria_rmbg/assets/22800918/ffc29902-7393-48bd-8f4e-6ca2ceae5a6e)

Thank you very much for your assistance.

**Comment by blessedcoolant** [comment]
This is just a node you can use inside the workflow editor. It will not show up anywhere in the Linear UI. 

As for the usage, you simply need to add the node in the Workflow Editor and drop your image on the node and press Invoke. The models will be automatically downloaded if they don't already exist. The image will be saved to your gallery.

**Comment by Kondzolko** [comment]
@blessedcoolant , everything is now working. Thank you for your help and your work on this project. I would greatly appreciate it if you could add this information to the README file, as it would be very helpful for users like me. Thank you so much!

**Comment by blessedcoolant** [comment]
No worries. I do have this in the Read Me.

`Add the BRIA AI Background Removal node. Plug in an image. That's it.`

Maybe I'll detail it out better.
